apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port the service will expose
      targetPort: 3000  # Port the container is listening on
      nodePort: 30080  # External port on the node for access
  type: NodePort  # Exposes the service externally on each node at the nodePort
