name: MongoDB Daily Backup to S3

on:
  workflow_dispatch:

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Install MongoDB Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-tools
        
    - name: MongoDB Database Backup
      run: |
        BACKUP_DIR="/tmp/db_backup"
        mongodump --uri="${{ secrets.MONGODB_URI }}" --out=$BACKUP_DIR

    - name: Upload Backup to S3
      run: |
        BACKUP_DIR="/tmp/db_backup/ats-db"
        if [ "$(ls -A $BACKUP_DIR)" ]; then
        echo "Uploading backup to S3 from: $BACKUP_DIR"
        find "$BACKUP_DIR" -type f | while read -r file; do
        aws s3 cp "$file" "s3://${{ secrets.AWS_BUCKET_NAME }}/$(basename "$file")"
        done
        else
        echo "Backup directory is empty. Skipping upload."
        exit 1
        fi

    - name: Clean up backup files
      run: |
        rm -rf /tmp/restore
