name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0

    - name: Set Kubernetes context
      run: kubectl config use-context dev 

    - name: Set Kubernetes context for dev
      run: kubectl cluster-info
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json
     
    - name: Validate Kubernetes YAML
      run: |
        kubectl apply --dry-run=client -f frontend-deployment.yaml
        kubectl apply --dry-run=client -f frontend-service.yaml
   
    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -n dev -f frontend-deployment.yaml
        kubectl apply -n dev -f frontend-service.yaml
        
    - name: Get Kubernetes Nodes Info
      run: |
       kubectl get nodes -o wide

    - name: Get Kubernetes Services
      run: |
        echo "Listing all Kubernetes services..."
        kubectl get services
        
    - name: Wait for frontend pod to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/frontend

    - name: list pods
      run: |
        kubectl get pods -n dev 

