name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0

    - name: Set Kubernetes context for KIND
      run: kubectl cluster-info
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json

    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        
    - name: Get Kubernetes Nodes Info
      run: |
       kubectl get nodes -o wide

    - name: Get Kubernetes Services
      run: |
        echo "Listing all Kubernetes services..."
        kubectl get services

    - name: Describe Pod
      run: |
        POD_NAME=$(kubectl get pods -l app=frontend -o jsonpath='{.items[0].metadata.name}')
        kubectl describe pod $POD_NAME

    - name: View Pod Logs
      run: |
        POD_NAME=$(kubectl get pods -l app=frontend -o jsonpath='{.items[0].metadata.name}')
        kubectl logs $POD_NAME

