name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0

    - name: Test Kubernetes connection
      run: kubectl get nodes
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json

    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        
    - name: Get Kubernetes Nodes Info
      run: |
       kubectl get nodes -o wide

    - name: Debug and Fetch Frontend Service Details
      run: |
        echo "Checking if the frontend service exists..."
        if kubectl get svc frontend; then
        echo "Fetching Frontend Service NodePort..."
           NODE_PORT=$(kubectl get svc frontend -o jsonpath='{.spec.ports[0].nodePort}')
          INTERNAL_IP=$(kubectl get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}')
          echo "Access your application at: http://${INTERNAL_IP}:${NODE_PORT}"
        else
          echo "Error: Frontend service not found. Please check your deployment."
          exit 1
        fi

    - name: Get Frontend Service NodePort
      run: |
        echo "Fetching Frontend Service Details..."
        kubectl get svc frontend -o jsonpath='{.spec.ports[0].nodePort}{"\n"}'
        
    - name: Display Application Access URL
      run: |
        NODE_PORT=$(kubectl get svc frontend -o jsonpath='{.spec.ports[0].nodePort}')
        INTERNAL_IP=$(kubectl get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}')
        echo "Access your application at: http://${INTERNAL_IP}:${NODE_PORT}"
    - name: Extract Node IPs
      run: |
        echo "Internal IPs:"
        kubectl get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="InternalIP")].address}{"\n"}{end}'
        
        echo "External IPs (if any):"
        kubectl get nodes -o jsonpath='{range .items[*]}{.status.addresses[?(@.type=="ExternalIP")].address}{"\n"}{end}'
