name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0

    - name: Test Kubernetes connection
      run: kubectl get nodes
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json

    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
