name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0
      
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json
   
    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        
    - name: Wait for frontend pod to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/frontend
        
    - name: Install ngrok
      run: |
        curl -Lo ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin
        rm ngrok.zip

    - name: Verify ngrok installation
      run: |
        ngrok version
