name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0     
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json
   
    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        
    - name: Wait for frontend pod to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/frontend

    - name: Download and Install Latest ngrok
      run: |
        curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin
        ngrok version

    - name: Authenticate ngrok
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok on Port 8080
      run: |
        nohup ngrok http 8080 &
        sleep 5
        curl -s localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
