name: Deploy to Kubernetes

on:
    workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Kubernetes with KIND
      uses: helm/kind-action@v1.6.0
      
        
    - name: Decode SECRETS_JSON_FILE and create Kubernetes Secret
      run: |
        echo "${{ secrets.SECRETS_JSON_FILE }}" | base64 --decode > secrets.json
        kubectl create secret generic api-keys-secret \
          --from-file=secrets.json
     
    - name: Validate Kubernetes YAML
      run: |
        kubectl apply --dry-run=client -f frontend-deployment.yaml
        kubectl apply --dry-run=client -f frontend-service.yaml
   
    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
        
    - name: Wait for frontend pod to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment/frontend
        
    - name: Install ngrok
      run: |
        curl -s https://ngrok.com/download | tar -xz
        sudo mv ngrok /usr/local/bin

    - name: Expose NodePort via ngrok
      run: |
        nohup ngrok http 8080 &
        sleep 5

    - name: Get ngrok Public URL
      run: |
        ngrok_url=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "ngrok public URL: $ngrok_url"






