name: Restore MongoDB Collection from S3

on:
  workflow_dispatch:

jobs:
  restore-collection:
    runs-on: ubuntu-latest
    env:
      BACKUP_FILE: "/tmp/db_backup"
      RESTORE_DIR: "/tmp/restore"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install MongoDB Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-tools

    - name: Create Restore Directory
      run: |
        mkdir -p "$RESTORE_DIR"
        echo "Created restore directory: $RESTORE_DIR"

    - name: Download Backup from S3 to Restore Directory
      run: |
        aws s3 cp s3://backupbucket-dev/ "$RESTORE_DIR" --recursive
        if [ "$(ls -A $RESTORE_DIR)" ]; then
          echo "Backup downloaded to $RESTORE_DIR"
        else
          echo "No files found in S3 bucket. Exiting..."
          exit 1
        fi

    - name: List Backup Files
      run: |
        echo "Listing contents of: $RESTORE_DIR"
        ls -R "$RESTORE_DIR" || echo "No files found in $RESTORE_DIR"

    - name: Restore Data to MongoDB Atlas
      run: |
        if [ -d "$RESTORE_DIR/dump" ]; then
          mongorestore --uri="${{ secrets.MONGODB_URI }}" --drop "$RESTORE_DIR/dump"
        else
          mongorestore --uri="${{ secrets.MONGODB_URI }}" --drop "$RESTORE_DIR"
        fi

    - name: Clean Up Backup Files
      if: always()
      run: |
        rm -rf "$RESTORE_DIR"
        echo "Cleaned up backup files."
