name: Restore MongoDB Collection from S3

on:
  workflow_dispatch:

jobs:
  restore-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install MongoDB Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-tools

    - name: Create a folder in /tmp for backup
      run: |
        # Create a new folder in /tmp
        BACKUP_DIR="/tmp/restore"
        mkdir -p "$BACKUP_DIR"
        echo "Created backup directory: $BACKUP_DIR"

    - name: Download Backup from S3 to the created folder
      run: |
        # Download files from S3 into the newly created folder
        aws s3 cp "s3://${{ secrets.AWS_BUCKET_NAME }}/" "$BACKUP_DIR" --recursive
        echo "Backup downloaded to $BACKUP_DIR"

    - name: List contents of the backup folder
      run: |
        # List contents of the backup folder to confirm files were downloaded
        ls -R "$BACKUP_DIR" || echo "No files found in $BACKUP_DIR"

    - name: Restore Data to MongoDB Atlas
      run: |
        # Restore the downloaded files to MongoDB Atlas
        mongorestore --uri="${{ secrets.MONGODB_URI }}" --db=dev-db --drop "$BACKUP_DIR"

    - name: Clean up backup files
      if: always()
      run: |
        # Clean up the backup files
        rm -rf "$BACKUP_DIR"
