name: Restore MongoDB Collection from S3

on:
  workflow_dispatch:

jobs:
  restore-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install MongoDB Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu $(lsb_release -sc)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-tools

    - name: Download Backup from S3
      run: |
        aws s3 cp "s3://${{ secrets.AWS_BUCKET_NAME }}/*" /tmp/restore --recursive
        
    - name: List files in /tmp after download
      run: |
        ls -R /tmp
        
    - name: Restore Data to MongoDB Atlas
      run: |
        mongorestore --uri="${{ secrets. MONGODB_URI }}" --db=dev-db --drop /tmp/restore

    - name: Clean up backup files
      run: |
        rm -rf /tmp/restore
